version: '3'
services:
  blockchain:
    build: packages/contracts
    ports:
      - "8545:8545"
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - apps/api/.env # configure postgres
    volumes:
      - decentralizedR:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '5432:5432'
volumes:
  decentralizedR: